yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_post, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:pk>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:pk>/comment/', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.internal_server_error'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField('Адрес группы', unique=True)
    description = models.TextField('Описание группы')

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField('Пост', help_text='Текст нового поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField('Комментарий:', help_text='Текст комментария')
    created = models.DateTimeField('Дата', auto_now_add=True)
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписавшийся пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Пользователь, на которого подписываются',
    )

    class Meta:
        constraints = models.UniqueConstraint(fields=['user', 'author'],
                                              name='unique_following')

yatube/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = {'text'}

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.cache import cache_page
from django.core.paginator import Paginator
from .models import Post, Group, User, Comment, Follow
from .forms import PostForm, CommentForm


def authorized_only(func):
    def check_user(request, *args, **kwargs):
        if request.user.is_authenticated:
            return func(request, *args, **kwargs)
        return redirect('/auth/login/')
    return check_user


POSTS_PER_PAGE = 10
TIME_OF_CASHING = 20


@cache_page(TIME_OF_CASHING)
def index(request):
    template = 'posts/index.html'
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_post(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group)
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, template, context)


def profile(request, username):
    template = 'posts/profile.html'
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    user = request.user
    following = False
    if user.is_authenticated and Follow.objects.filter(
            user=user, author=author):
        following = True
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, template, context)


def post_detail(request, pk):
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post.objects, pk=pk)
    comments = Comment.objects.filter(post=post)
    form_comment = CommentForm(request.POST or None)
    post_obj = Post.objects.all()
    context = {
        'post': post,
        'comments': comments,
        'form': form_comment,
        'post_obj': post_obj,
    }
    return render(request, template, context)


@authorized_only
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None, files=request.FILES or None)
    if not form.is_valid():
        return render(request, template, {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user)


def post_edit(request, pk):
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, pk=pk)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.user != post.author:
        return redirect('posts:post_detail', pk=pk)
    if not form.is_valid():
        context = {
            'form': form,
            'is_edit': True,
            'post': post,
        }
        return render(request, template, context)
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:post_detail', pk=pk)


@authorized_only
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', pk=pk)


@authorized_only
def follow_index(request):
    template = 'posts/follow.html'
    authors = Follow.objects.filter(user=request.user).values_list(
        'author', flat=True)
    post_list = Post.objects.filter(author__in=authors)
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


@authorized_only
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if (request.user != author):
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:follow_index')


@authorized_only
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
    {% block title %}Новый пост{% endblock %}
    {% block content %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">       
              Новый пост             
            </div>
            <div class="card-body">    
              <form method="post" enctype="multipart/form-data"
              action="{% if is_edit %}{% url 'posts:post_edit' post.pk %}{% else %}{% url 'posts:post_create' %}{% endif %}">   
                <input type="hidden" name="csrfmiddlewaretoken" value="">
                {% csrf_token %}           
                <div class="form-group row my-3 p-3">
                  {{ form.as_table }}
                <div class="d-flex justify-content-end">
                  <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    {% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block title %}
    Последние обновления на сайте
    {% endblock %}

    {% block content %}     
      <h1>Последние обновления на сайте</h1>
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" >
            {% endthumbnail %}      
            <p>
              {{ post.text }}
            </p>
            {% if post.group %}
              <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
              <p><a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a></p>

            {% endif %}
            
          </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    {% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block title %}
      {{ group }} 
    {% endblock %}
      
    {% block content %}
      <h1> 
        {{ group.title }}
      </h1>
      <p>
        {{ group.description }}
      </p>
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}       
          <p>
            {{ post.text }}
          </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>       
        </article>
        {% if not forloop.last %}
          <hr>
        {% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
    {% block title %}
    Последние обновления на сайте
    {% endblock %}

    {% block content %}     
      <h1>Последние обновления на сайте</h1>
        {% include 'posts/includes/switcher.html' %}
        {% for post in page_obj %}
          <article>
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a> 
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" >
            {% endthumbnail %}      
            <p>
              {{ post.text }}
            </p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
            {% if post.group %}
              <p><a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a></p>
            {% endif %}
            
          </article>
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    {% endblock %}
    

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title %}
    {{ post.text }}
  {% endblock %}
  {% block content %}  
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          <!-- если у поста есть группа -->   
            <li class="list-group-item">
              Группа: {{ post.group }}
              {% if post.group %}
                <p><a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a></p>
              {% endif %}
            </li>
            <li class="list-group-item">
              Автор: {{ post.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span > {{ post.author.posts.count }} </span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text }}
        </p>
        <!-- эта кнопка видна только автору -->
        {% if request.user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
          редактировать запись
        </a>
        {% endif %}

        {% load user_filters %}
        {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
              <form method="post" action="{% url 'posts:add_comment' post.id %}">
                {% csrf_token %}      
                <div class="form-group mb-2">
                  {{ form.text|addclass:"form-control" }}
                </div>
                <button type="submit" class="btn btn-primary">Отправить</button>
              </form>
            </div>
          </div>
        {% endif %}

        {% for comment in comments %}
          <div class="media mb-4">
            <div class="media-body">
              <h5 class="mt-0">
                <a href="{% url 'posts:profile' comment.author.username %}">
                  {{ comment.author.username }}
                </a>
              </h5>
                <p>
                {{ comment.text }}
                </p>
              </div>
            </div>
        {% endfor %}
      </article>
    </div>
  {% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title %}
    Профайл пользователя {{ author }}
  {% endblock %}

  {% block content %}
  <div class="mb-5">  
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% elif request.user != author %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
    {% endif %}
  </div>
  {% for post in page_obj %} 
    <article>
      <ul>
      <li>
        Автор: {{ author.get_full_name }}
        <a href="{% url 'posts:profile' author.username %}">все посты пользователя</a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %} 
      <p>
        {{ post.text }}
      </p>
      <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
    </article>       
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>     
        <!-- Остальные посты. после последнего нет черты -->
        {% if not forloop.last %}
            <hr>
        {% endif %}
      {% endfor %} 
        <!-- Здесь подключён паджинатор -->  
    {% include 'posts/includes/paginator.html' %}
  {% endblock %}